[package]
name = "secretcli"
version = "0.1.0"
authors = [
  "Guy Garcia <guysebastiangarcia@gmail.com>",
  "hydropump3 <3ki2fiay@anonaddy.me>",
]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []

[dependencies]
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.67"}
